version: "3.7"

services:
  m-moments:
    image: kingwrcy/m-moments:latest
    ports:
      - "37212:8787"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=m-moments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./m-moments:/app/upload
